import { Post, PostStatus } from '@/features/posts/types';

export const posts: Post[] = [
  {
    id: 'post-1',
    communityId: 'downtown-dubai',
    title: 'Dubai Fountain show schedule this weekend?',
    body: 'Is the fountain running on the usual 30-minute schedule this weekend, or is it extended for the holiday?',
    authorName: 'jordan.k',
    createdAt: '2026-06-28T09:15:00.000Z',
    status: PostStatus.Sent,
  },
  {
    id: 'post-2',
    communityId: 'downtown-dubai',
    title: 'Resident parking near The Dubai Mall entrance',
    body: 'Does anyone have tips for finding resident parking during weekend mall traffic?',
    authorName: 'priya.s',
    createdAt: '2026-06-30T14:02:00.000Z',
    status: PostStatus.Sent,
  },
  {
    id: 'post-3',
    communityId: 'dubai-hills-estate',
    title: 'Central Park playground finally open!',
    body: 'The new playground by the community centre opened this morning — kids are loving the climbing frame.',
    authorName: 'marcus.b',
    createdAt: '2026-06-29T07:40:00.000Z',
    status: PostStatus.Sent,
  },
  {
    id: 'post-4',
    communityId: 'dubai-hills-estate',
    title: 'Construction noise near Maple this week',
    body: 'Anyone else noticing more construction noise near the Maple villas the past few mornings?',
    authorName: 'elena.v',
    createdAt: '2026-07-01T11:20:00.000Z',
    status: PostStatus.Sent,
  },
  {
    id: 'post-5',
    communityId: 'the-springs',
    title: 'Lake walk lighting fixed',
    body: 'The lighting along the lake walk near Springs 9 has finally been repaired after months of reports.',
    authorName: 'sam.r',
    createdAt: '2026-07-02T16:45:00.000Z',
    status: PostStatus.Sent,
  },
  {
    id: 'post-6',
    communityId: 'arabian-ranches',
    title: 'Polo club family day this Saturday',
    body: 'The Els Club polo grounds are hosting a family day this Saturday — food trucks and pony rides for the kids.',
    authorName: 'noah.t',
    createdAt: '2026-06-27T18:10:00.000Z',
    status: PostStatus.Sent,
  },
];
